# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

language: ruby

branches:
  only:
    - master
    - travis

rvm:
  - 1.9.3
  - 2.0.0

jdk:
  - openjdk7

services:
  - mongodb

before_script:
  - rake bundle:clean
  - rake bundle:install

script:
  - SERVER=start bundle exec rake test:all

gemfile:
  - $PWD/elasticsearch-model/gemfiles/3.0.gemfile
  - $PWD/elasticsearch-model/gemfiles/4.0.gemfile

notifications:
  disable: true
