# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

language: ruby

branches:
  only:
    - master
    - travis

rvm:
  - 1.9.3
  - 2.0.0

jdk:
  - openjdk7

install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.tar.gz | tar xz -C /tmp || true

services:
  - mongodb

before_script:
  - rake bundle:clean
  - rake bundle:install

script:
  - SERVER=start TEST_BUILD_REF=origin/0.90 TEST_CLUSTER_COMMAND=/tmp/elasticsearch-0.90.10/bin/elasticsearch TEST_CLUSTER_NODES=1 bundle exec rake test:all

gemfile:
  - $PWD/elasticsearch-model/gemfiles/3.0.gemfile
  - $PWD/elasticsearch-model/gemfiles/4.0.gemfile

notifications:
  disable: true
